version: "3.3"
services:
  superserver:
    image: pivotalrabbitmq/rabbitmq-stream
    hostname: superserver
    container_name: superserver
    ports:
    - "5670:5670"
    - "15670:15670"
    - "5550:5550"
    - "15690:15690"
    volumes:
    - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq2.conf
    - ./mnesia:/var/lib/rabbitmq/mnesia/rabbit@superserver
    - type: bind
      source: ./.bash_history
      target: /var/lib/rabbitmq/.bash_history
    networks:
    - rabbitmq_super_net
    environment:
    - RABBITMQ_DEFAULT_USER=rabbit_admin
    - RABBITMQ_DEFAULT_PASS=.123-321.
    - RABBITMQ_CONFIG_FILES=/etc/rabbitmq/rabbitmq2.conf
    # - RABBITMQ_ADVANCED_CONFIG_FILE=/etc/rabbitmq/advanced.config
    - RABBITMQ_NODENAME=rabbit@superserver
    - RABBITMQ_NODE_PORT=5670
    #- RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS='rabbitmq_stream advertised_host superserver'
networks:
  rabbitmq_super_net:
    name: super_net
#docker run --name superserver -p 5552:5552 -p 5672:5672 -p 15672:15672 \
#-e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS='-rabbitmq_stream advertised_host localhost' pivotalrabbitmq/rabbitmq-stream